services:
  qwen-api:
    build:
      context: ../QWEN-API
      dockerfile: Dockerfile
    image: registry.gitlab.com/tuanxx31/gemini-qwen-api/qwen-api:latest
  gemini-api:
    build:
      context: ../Gemini-API
      dockerfile: Dockerfile_new
    image: registry.gitlab.com/tuanxx31/gemini-qwen-api/gemini-api:latest
  seedream-api:
    build:
      context: ../SEEDREAM-API
      dockerfile: Dockerfile
    image: registry.gitlab.com/tuanxx31/gemini-qwen-api/seedream-api:latest