services:
  qwen-api:
    image: registry.gitlab.com/tuanxx31/qwen-api:latest
    container_name: qwen-api
    restart: unless-stopped
    ports:
      - "8990:8990"
    volumes:
      - ./config.json:/app/config.json:ro
    networks:
      shared-network:
        aliases:
          - qwen-api
    environment:
      - PYTHONUNBUFFERED=1

networks:
  shared-network:
    external: true
